# Python 공식 이미지 사용
FROM python:3.9

WORKDIR /app

# 환경 변수 설정
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# 의존성 파일 복사 및 설치
COPY requirements.txt /app/
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

# 프로젝트 소스 복사
COPY . .

# Gunicorn 실행 명령어 (포트 8000 사용)
CMD [ "gunicorn", "--bind", "0.0.0.0:8000", "--workers", "3", "Devjs.wsgi.application" ]